language: go

go:
  - 1.8
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get github.com/golang/dep/...
  - dep ensure -update
  - go get github.com/golang/lint/golint
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/client9/misspell/cmd/misspell

script:
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -race $(go list ./... | grep -v /vendor/)
  # workaround for vendor folder
  - rm -rf vendor/*
  - diff <(echo -n) <(gofmt -s -d .)
  - ineffassign .
  - misspell -error .

after_script:
  - golint $(go list ./... | grep -v /vendor/)

before_deploy: ./hack/release.sh

deploy:
  provider: releases
  api_key:
    secure: Y0hnzcQxEKARiCRrt3NUQBiH4keAG/9AYuq6Ri9G0BlpxImPVWZOthNUq+ZKSN2fbPekIpccGGOw363/4OWz4XSy4nKfiM4qhAsV1/0kAHJsF++9UgrVaEZ408Th2I7GdE+zKelSWpTiptgo6M9LDE8tHAjTQ2iOK/0D3pEgmPyUtlpQyOtQjsMR0f9au6Qlx/OSd5/UZWAyDKarDYnhndZhy3afR56M0CKgjgvUVCtKuEwgSII6HUW5xy20BA7dH2DuQdpWhyWeRdmUq8x91yVKVkASHlqofE3LkTcN7PphKKf9s6U2NEZr4AWYx5QVwKWLJTYON3Xn7W+C9ESfSgNzq8gPZz7qWWmTde/1hJloUAMBrPXi+Dk9aYQOGYQr2eolr2WFeG9XWsGFTj4mHeS5jkfNDhXzKHBH4PmCCaDUppCpKiAMhS5RAQ+T6Bde13BIkTGkWiNa8yjK5rUdBt47jGRmwsp0C+vWO7njUd0YHNAalW23FzbptqfBMxyttuG8o678+mqXges7Njv1fbaHgC6sdIKyZ+5bnrtCYx5GhfhJAqOTyfD8J/JSEtOu3/uLO74yl+mth8f8cAhIjvbG56rxetM6NrsmcK7koxhe9KhPWfoK+kwdp4OkxuG1XMX4kiWaI/QZtUPfw9PRtwKmb+30rw3vx5Z8KAHLwCE=
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    repo: yaproxy/yap
    tags: true
