language: go

go:
  - 1.8
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get -t ./...
  - go get github.com/golang/lint/golint
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/client9/misspell/cmd/misspell

script:
  - diff <(echo -n) <(gofmt -s -d .)
  - ineffassign .
  - misspell -error .
  - go vet ./...
  - go test -race ./...

after_script:
  - golint ./...
